### ISSUE TITLE
FA-Connect

### ISSUE THREAD

**Issue by fstoelwinder** [JoeriSmits/FA_Ideas_Issues#5] opened 2016-12-10 11:29 UTC
Thank you for the effort to submit an issue with the Flight-Academy Dashboard.
Issues must be reported in english.

##ERRORS
In order to understand the issue better we would like you to describe the following things in the description:
  * What operating system and version are you using? (For example: Windows 10)
  * What browser and version are you using? (For example: Chrome v49) http://www.whatsmybrowser.org/
  * What is the URL where the issue is of effect? (For example: http://dashboard.flight-academy.nl/home)
  * What is the expected behaviour and what is the actual behaviour?
  * Describe the steps to reproduce the problem.

The above is only for errors in the application.

##FEATURES
To submit features please take a look at the 'Issues' tab and see if your feature is not already asked.
If the feature is already asked please take a look at the issue and see if you can contribute by typing a comment.

If your feature is not already asked you may create a new issue. Please describe the following things in the description:
  * Write a description of the feature you would like (You may add images if these are an addition to your description).

**Comment by fstoelwinder** [comment] 2016-12-10 11:31
Ik kan in FA-connect geen vluchtplan indienen. Is het mogelijk om deze module toe te voegen zoals dat bij IVAO ook gaat?

**Comment by JoeriSmits** [comment] 2016-12-10 20:22
Vluchtplannen worden zometeen via het dashboard ingevuld. Deze kunnen dan ook worden bewaard en bekeken en beoordeelt door trainers.

**Comment by JoeriSmits** [comment] 2016-12-10 20:23
Duplicate of issue #4

**Closed by JoeriSmits** 2016-12-10 20:23 UTC
Labels: duplicate
